### ISSUE TITLE
Sprites

### ISSUE THREAD

**Issue by Nienhaus** [Xhuis/AquaStation#1]
I have no idea how to contact you. If you want help with spritework feel free to contact me.

**Comment by Xhuis** [comment]
\>posting a non-issue in the issues tab
LOL BANNED

Seriously though, thank you very much for your offer for help! I appreciate it a lot. For now, just keep track of the forum thread - I'll be posting there if I need any sprites.

**Comment by Nienhaus** [comment]
Not going to lie, I forgot that I could just message you on the forums.
